import { imageIcon, printer } from "app/assets/Icons";

const getActionItem = () => {
  return (
    <div style={{ display: "flex", gap: "20px" }}>
      <img src={imageIcon} alt="" />
      <img src={printer} alt="" />
    </div>
  );
};

export const searchTable = [
  {
    Client: "John Doe",
    Email: "john.doe@gmail.com",
    Date: "06/06/21",
    Address: "123 Broadway Avenue",
    City: "Tornoto",
    Provience: "Oregon",
    Country:"Canada",
    Action: getActionItem(),
  },
  {
    Client: "John Doe",
    Email: "john.doe@gmail.com",
    Date: "06/06/21",
    Address: "123 Broadway Avenue",
    City: "Tornoto",
    Provience: "Oregon",
    Country:"Canada",
    Action: getActionItem(),
  },
  {
    Client: "John Doe",
    Email: "john.doe@gmail.com",
    Date: "06/06/21",
    Address: "123 Broadway Avenue",
    City: "Tornoto",
    Provience: "Oregon",
    Country:"Canada",
    Action: getActionItem(),
  },
  {
    Client: "John Doe",
    Email: "john.doe@gmail.com",
    Date: "06/06/21",
    Address: "123 Broadway Avenue",
    City: "Tornoto",
    Provience: "Oregon",
    Country:"Canada",
    Action: getActionItem(),
  },
  {
    Client: "John Doe",
    Email: "john.doe@gmail.com",
    Date: "06/06/21",
    Address: "123 Broadway Avenue",
    City: "Tornoto",
    Provience: "Oregon",
    Country:"Canada",
    Action: getActionItem(),
  },
  {
    Client: "John Doe",
    Email: "john.doe@gmail.com",
    Date: "06/06/21",
    Address: "123 Broadway Avenue",
    City: "Tornoto",
    Provience: "Oregon",
    Country:"Canada",
    Action: getActionItem(),
  },
  {
    Client: "John Doe",
    Email: "john.doe@gmail.com",
    Date: "06/06/21",
    Address: "123 Broadway Avenue",
    City: "Tornoto",
    Provience: "Oregon",
    Country:"Canada",
    Action: getActionItem(),
  },
  {
    Client: "John Doe",
    Email: "john.doe@gmail.com",
    Date: "06/06/21",
    Address: "123 Broadway Avenue",
    City: "Tornoto",
    Provience: "Oregon",
    Country:"Canada",
    Action: getActionItem(),
  },
  {
    Source: "John Doe",
    Email: "john.doe@gmail.com",
    Date: "06/06/21",
    Address: "123 Broadway Avenue",
    City: "Tornoto",
    Provience: "Oregon",
    Country:"Canada",
    Action: getActionItem(),
  },
  {
    Source: "John Doe",
    Email: "john.doe@gmail.com",
    Date: "06/06/21",
    Address: "123 Broadway Avenue",
    City: "Tornoto",
    Provience: "Oregon",
    Country:"Canada",
    Action: getActionItem(),
  },
  {
    Source: "John Doe",
    Email: "john.doe@gmail.com",
    Date: "06/06/21",
    Address: "123 Broadway Avenue",
    City: "Tornoto",
    Provience: "Oregon",
    Country:"Canada",
    Action: getActionItem(),
  },
  {
    Source: "John Doe",
    Email: "john.doe@gmail.com",
    Date: "06/06/21",
    Address: "123 Broadway Avenue",
    City: "Tornoto",
    Provience: "Oregon",
    Country:"Canada",
    Action: getActionItem(),
  },
];
