export const singleShipmentInitValues = {
  OrigincompanyName: "",
  OriginfirstName: "",
  OriginlastName: "",
  OriginaddressLine1: "",
  OriginaddressLine2: "",
  Origincity: "",
  OriginpostalCode: "",
  OriginprovinceState: "",
  Origincountry: "",
  OrigincontactNumber: "",
  OriginalternateNumber: "",
  OriginemailAddress: "",
  OriginadditionalNotes: "",
  DestinationcompanyName: "",
  DestinationfirstName: "",
  DestinationlastName: "",
  DestinationaddressLine1: "",
  DestinationaddressLine2: "",
  Destinationcity: "",
  DestinationpostalCode: "",
  DestinationprovinceState: "",
  Destinationcountry: "",
  DestinationtactNumber: "",
  DestinationalternateNumber: "",
  DestinationemailAddress: "",
  DestinationadditionalNotes: "",
  Category: "",
  ShipmentWeight: "",
  Length: "",
  Width: "",
  Height: "",
  Pieces: "",
  ShipmentCost: "",
  ShipmentDescription: "",
  shipmentTime:"",
  shipmentDate:"",
  whatToDo:""
};
